### ISSUE TITLE
localization & internationalization (translation)

### ISSUE THREAD

**Issue by syusui-s** [syusui-s/rabbit#10]
**Is your feature request related to a problem? Please describe.**

Currently, Japanese is the only supported language.
There are many Nostr fans who use other languages.
It would be great if Rabbit supports another languages.

**Describe the solution you'd like**
Introduce some i17n library and replace hard-coded texts.

**Comment by mbarulli** [comment]
+1

**Comment by syusui-s** [comment]
b3a0bfe772cfb5f17e23423b9fc75ead1a49cb0f

I added an English translation with this commit.
