### ISSUE TITLE
不正な npub を投稿した場合に本文が壊れる

### ISSUE THREAD

**Issue by penpenpng** [syusui-s/rabbit#18]
**バグの説明**
`npub1` から始まるが valid でない文字列が含まれる投稿を試みて TL に表示する、または他クライアントから取得したそのような投稿を TL で閲覧する際、本文が壊れる。

**再現手順**
1. `npub1namazuv2` (桁数が足りない) を投稿すると本文として `npub1namazuv2npunpub1namazuv2npub1namazuv2` を得る。(参考: `nostr:note1s5muz3dwjdrp08lmqxq00h62ll6er2hf076lwp9pjtmyy0atgnrsgywyjf`) 
2. `桁数があっているが不正な場合 npub133vj8ycevdle0cq8mtgddq0xtn34kxkwxvak983dx0u5vhqnycyqj6tcz1` (桁数は正しいが不正な文字が含まれる (最後の `1`)) を投稿すると本文として `桁数があっているが不正な場合 桁数があっているが不正な場合 桁数があっているが不正な場合 桁数があっているが不正な場合 npub133vj8ycevdle0cq8mtgddq0xtn34kxkwxvak983dx0u5vhqnycyqj6tcz桁数があっているが不正な場合 桁数があっているが不正な場合 npub133vj8ycevdle0cq8mtgddq0xtn34kxkwxvak983dx0u5vhqnycyqj6tcz桁数があっているが不正な場合 桁数があっているが不正な場合 桁数があっているが不正な場合 npub133vj8ycevdle0cq8mtgddq0xtn34kxkwxvak983dx0u5vhqnycyqj6tcz桁数があっているが不正な場合 npub133vj8ycevdle0cq8mtgddq0xtn34kxkwxvak983dx0u5vhqnycyqj6tcz桁数があっているが不正な場合 桁数があっているが不正な場合 npub133vj8ycevdle0cq8mtgddq0xtn34kxkwxvak983dx0u5vhqnycyqj6tcz桁数があっているが不正な場合 npub133vj8ycevdle0cq8mtgddq0xtn34kxkwxvak983dx0u5vhqnycyqj6tcz1` を得る。(参考: `nostr:note1ncq3wkd04paxuv7tsne8vek0zg72hvaepuk90jpsztqzggj3pakqem8y7p`)

**期待される挙動**
npub が不正だった場合は plaintext として解釈される。

**スクリーンショット**
![ss000](https://user-images.githubusercontent.com/24215933/236388927-5ca735fc-8cbc-4ff5-8326-b3c4658a1809.png)

**デスクトップ （該当する場合は以下の情報を埋めてください）:**
 - OS: Windows10
 - ブラウザ:  Chrome
 - バージョン: 112.0.5615.138

**補遺**
Rabbit から投稿することによって現象を再現する場合、他クライアントからの投稿によって再現する場合と比べて2倍長くなる傾向がある。

**Comment by syusui-s** [comment]
ご報告ありがとうございます。

18e9ddd16ad73b263c565280dff580ce657678f4 で対応しました。
問題がないかどうかご確認いただき、問題がなければ本課題をクローズしていただけますか。

**Comment by penpenpng** [comment]
迅速なご対応ありがとうございました！問題なさそうに見えますので閉じさせていただきます～
