### ISSUE TITLE
正しいLNURLであるにもかかわらず、登録が行えない

### ISSUE THREAD

**Issue by Memory-of-Snow** [syusui-s/rabbit#20]
**バグの説明**
プロフィールから、「LNURLアドレス / ライトニングアドレス」に正しいと思われるLNURLを入力しても「指定されている形式で入力してください」と表示され、登録が行えない

**再現手順**
発生させる手順を説明してください:
1. '設定'に移動
2. プロフィール欄の'編集'をクリック
3. 'LNURLアドレス / ライトニングアドレス'にLNURLをを入力する。
4. 保存をクリックする。
5. 「指定されている形式で入力してください」エラーが表示される

**期待される挙動**
エラー表示なく、LNURLアドレスが登録されてほしい

**デスクトップ （該当する場合は以下の情報を埋めてください）:**
 - OS:Windows10
 - ブラウザ: Chrome
 - バージョン:113.0.5672.93

**追加の情報**
該当するLNURLに関しては、iris.to上から登録できたので適正なものであると判断しました。
iris.toで登録後、既に記入されている「LNURLアドレス / ライトニングアドレス」欄に変更を行わず、
保存をクリックしても「指定されている形式で入力してください」エラーが表示されます。

**Comment by syusui-s** [comment]
@Memory-of-Snow

ご報告ありがとうございます。

今の入力ルールではLNURLが大文字のみしか許可しておらず、それが影響している可能性があります。
もし小文字で入力していた場合は `lnurl1...`ではなく、`LNURL1...` でうまく入力できるかどうかご確認いただけますか。

もし関係なさそうであれば、検証するために入力したLNURLを教えていただけますか。

**Comment by Memory-of-Snow** [comment]
LNURL1...形式では無事に登録できました。

**Comment by Memory-of-Snow** [comment]
https://github.com/lnurl/luds/blob/luds/01.mdを見ると、

>>Bech32-encoded LNURLs can both be uppercase or lowercase, but not mixed case. When used in QR-Codes they SHOULD be uppercase.

とのことなので、入力ルールで小文字も受け付けるのはどうでしょうか。

**Comment by Memory-of-Snow** [comment]
確認しました。対応ありがとうございます。
