### ISSUE TITLE
ホーム欄が真っ白になる時がある

### ISSUE THREAD

**Issue by Memory-of-Snow** [syusui-s/rabbit#21]
**バグの説明**
「ホーム」コラムが空白でポストが表示されないことがある。

**再現手順**
発生させる手順を説明してください:
条件が不確定
ブックマークからhttps://syusui-s.github.io/rabbit/を開いた際に時折発生することがある。

**期待される挙動**
タイムラインが表示されてほしい

**スクリーンショット**
<img width="262" alt="スクリーンショット 2023-05-15 120304" src="https://github.com/syusui-s/rabbit/assets/98633948/9df94e89-eeab-45b9-b3d0-8064411f1247">

**デスクトップ （該当する場合は以下の情報を埋めてください）:**
 - OS: Windows10
 - ブラウザ: Chrome
 - バージョン:113.0.5672.93

**Comment by syusui-s** [comment]
note1dna27t9arwkxtlhr3k5gxvf72q5ldryd7ucdyc3mfwlm0hk2hsmsga8ez3

note1e84cx0ymz6h2w4mutjm736fdmqayp8hmpphmjargfywwsyha4m5sqpm7w8

note1cu7trkcnw28hu3w5ckkpxu20dccx8d524w9v7cwlnfrntk37x75qq03re0

**Comment by Memory-of-Snow** [comment]
調査中了解

**Comment by syusui-s** [comment]
note16x36rt42fea34c6f8rcqm4hzwcamqa432nae2ch80srewvt90epq2xsnqw
note15cxgu0vzqelgjww2jyqzhmm78nppvh4rvd3ae0c2xtwadhfsg8msc9v5hp

dca108084aa415558f400dffee4fe8b7b4815685 と関連？

**Comment by syusui-s** [comment]
note1333q4nd64grz332xxjnqunggwh6rufsdy3e360gj4uru0gpguykqez5zvl
https://github.com/syusui-s/rabbit/commit/d8f9214a83c05c6f6e21846209a464777a0ff1a2

fixed with this

**Comment by syusui-s** [comment]
@Memory-of-Snow
1月7日の修正でおそらく発生しなくなっているはずです。
問題が発生していなければクローズしていただけると嬉しいです。
