### ISSUE TITLE
フォロワー数が0になる

### ISSUE THREAD

**Issue by kazuyasi** [syusui-s/rabbit#76]
**バグの説明**
プロフィール画面から、フォロワー数を読み込むと、0になってしまう。

**再現手順**
発生させる手順を説明してください:

1. 歯車マークをクリックして'設定'に移動
2. 'プロフィール'をクリック
3. '開く'をクリック
4. フォロワー数の隣の'読み込む'をクリック
5. 0と表示される（他サイトで0より大きいことを確認済）

**期待される挙動**
正確なフォロワー数が表示される。

**スクリーンショット**
![スクリーンショット 2024-01-05 100441](https://github.com/syusui-s/rabbit/assets/1835581/bbc462f0-963c-4140-9e30-b17f197e56af)

**デスクトップ （該当する場合は以下の情報を埋めてください）:**

- OS: Windows 11
- ブラウザ: Edge
- バージョン: 120.0.2210.91

**追加の情報**
とくにありません。

**Comment by syusui-s** [comment]
ご報告ありがとうございます。
709fbbe で修正しましたので、クローズします。

**Comment by kazuyasi** [comment]
修正を確認しました。ありがとうございます。
