### ISSUE TITLE
+の手前でURLがリンク切れ

### ISSUE THREAD

**Issue by koteitan** [syusui-s/rabbit#8]
+を含むURLをポストしたときにリンクが+の手前で切れてしまうようです。
- 問題のポスト:https://iris.to/note17yzjq7r3t33x6yf47fll3fll3umdhq0ssyg57ay6akvsrrhh707qvn8592
- それのRabbitでの見た目:https://iris.to/note1asgz7x64tnc9p8l93s7t6uuynszulw7evjktqeee0fp5stq5d8fsxqt2jl
- 環境: 3/20 14:00 の Rabbit+Windows11+Chrome 111.0.5563.65 64bit

**Comment by syusui-s** [comment]
@koteitan 

以前のコミットで対応しました。修正を確認できているため、私のほうでクローズします。
ご報告ありがとうございました。

https://github.com/syusui-s/rabbit/commit/677f9e0e0362df00c2c0a0452e8b53d8ef5abb29#diff-ed18763d2be6ce35cbbfd37618b83c8c89ec7953b033008e32ef7758692dccddR65-R82

note1ju9d96ksk4nt33yqeddrm5g6myhx29aykkv5j28jd3cpjm0dpwpqkxl8cv

万が一、関連して他の問題を見つけられた場合は別のIssueを作っていただけましたら幸いです。
