### ISSUE TITLE
Content empty in Yandex was working a day or two ago

### ISSUE THREAD

**Issue by dunkfan** [syusui-s/rabbit#80]
No content showing in Yandex (Mint Linux)
Was working a day or two ago...

nos2x private key installed in browser and ready
Navigate to https://rabbit.syusui.net/#/
Nothing shown except the button bar on the left.

**Comment by syusui-s** [comment]
`rabbit.syusui.net` is working in my environment... 

Please try:

- Give Rabbit an access to signer extension, again.
    - There is a case where the user revoked an access by mistake.
    - Open the extension options.
    - You can see the list of permissions for each web sites. And, find `rabbit.syusui.net`
    - Click "reset" button or "delete" button of `rabbit.syusui.net`
    - Try to access https://rabbit.syusui.net/
    - The confirmation window will be shown.
- Open Rabbit in other browsers such as Chromium and Firefox
    - If it works, there should be differences between browsers such as extensions and features.
- Open the old URL of Rabbit: https://syusui-s.github.io/rabbit/
    - You can see "Close" button in the bottom of the page.
    - If it works, it might relates to domain.

**Comment by dunkfan** [comment]
A restart of Linux fixed it.
The history in the browser wasnt working. After closing the broweser there were still many yandex processes running.

Thanks
